### ISSUE TITLE
app: GitBook

### ISSUE THREAD

**Issue by IvanMiroshin** [atomery/webcatalog#570]
# App Submission

- **Name:** GitBook
- **URL:** https://www.gitbook.com/
- **Category:** Developer Tools
- **Icon:** https://uploads-ssl.webflow.com/5c349f90a3cd4515d0564552/5ca4a7f06fd13e4aa1da6098_Logo%2Bsquare256.png

**Comment by quanglam2807** [comment]
Thanks for the submission. Added with #621.
