### ISSUE TITLE
app: BBC News

### ISSUE THREAD

**Issue by macta** [atomery/webcatalog#573]
# App Submission

- **Name:**
BBC News
- **URL:**
https://www.bbc.co.uk
- **Category:**
News

- **Icon:**
![image](https://user-images.githubusercontent.com/5553623/75436646-d7bb8a00-594c-11ea-8177-c3f9dea611e7.png)

**Comment by macta** [comment]
A better icon

![bbc](https://user-images.githubusercontent.com/5553623/75443442-50284800-5959-11ea-8f7f-40acb5b33c6e.png)

**Comment by quanglam2807** [comment]
Thanks for the submission. Added with #621.

**Comment by quanglam2807** [comment]
Btw, I think I got the icon from the App Store :)
