### ISSUE TITLE
app: Adobe color

### ISSUE THREAD

**Issue by Wesley444** [atomery/webcatalog#603]
# App Submission

- **Name:** Adobe color
- **URL:** https://color.adobe.com/create
- **Category:** Graphics & Design

- **Icon:** 
![Kuler00_logo](https://user-images.githubusercontent.com/61077862/76599129-01f47680-650d-11ea-945c-a33c947119f2.png)

**Comment by quanglam2807** [comment]
Thanks for the submission. Added with #621.
